/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.wleditor.app;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class mipmap {
        public static final int ic_launcher=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int clipboard_help=0x7f040006;
        public static final int copy=0x7f040013;
        public static final int cut=0x7f040012;
        public static final int diamond_navigation=0x7f040005;
        public static final int fatal_error_msg=0x7f040003;
        public static final int find_replace=0x7f040016;
        public static final int menu_edit=0x7f040009;
        /**  Menu strings 
         */
        public static final int menu_file=0x7f040008;
        public static final int menu_help=0x7f04000b;
        public static final int menu_view=0x7f04000a;
        public static final int ministro_needed_msg=0x7f040002;
        public static final int ministro_not_found_msg=0x7f040001;
        /**  File operations 
         */
        public static final int new_file=0x7f04000c;
        public static final int open_file=0x7f04000d;
        public static final int paste=0x7f040014;
        public static final int redo=0x7f040011;
        public static final int save_as=0x7f04000f;
        public static final int save_file=0x7f04000e;
        public static final int search_help=0x7f040007;
        public static final int select_all=0x7f040015;
        /**  Edit operations 
         */
        public static final int undo=0x7f040010;
        /**  WordStar specific strings 
         */
        public static final int wordstar_help_title=0x7f040004;
    }
}
