name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # 手動実行も可能

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Qt6
      run: |
        sudo apt update
        sudo apt install -y qt6-base-dev qt6-tools-dev cmake build-essential
    
    - name: Configure and Build
      run: |
        mkdir build-release
        cd build-release
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j$(nproc)
    
    - name: Create Release Asset
      run: |
        cd build-release
        cp wordstar-editor wleditor-${{ github.ref_name }}-linux-x64
        chmod +x wleditor-${{ github.ref_name }}-linux-x64
    
    - name: Upload Release Asset
      uses: actions/upload-artifact@v4
      with:
        name: wleditor-linux-x64
        path: build-release/wleditor-${{ github.ref_name }}-linux-x64

  # 将来のARM/Android用ビルドジョブもここに追加予定
  
  create-release:
    needs: [build-linux-x64]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          wleditor-linux-x64/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
